Hw12 13 14 15 calendar
v4-nikishin/hw pull request #12
Opened 2022-12-22 08:53 UTC by v4-nikishin

2022-12-22 16:16 UTC, dshemin requested changes

2022-12-22 16:16 UTC, dshemin commented on hw12_13_14_15_calendar/cmd/calendar/config.go
> +func LoadConfigFile(cfg interface{}, filePath string) error {
Важно:

А зачем нам тут пустой интерфейс? У нас же есть структура конфигурационного файла.

В целом также сигнатура функции не очень. Почему бы не:

```
func Load(filePath string) (Config, error) {}
```

2022-12-22 16:16 UTC, dshemin commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +		panic(fmt.Sprintf("Failed to configure service %s", err))
Критично:

Никогда не используйте панику в проектах. Тут мы можем спокойно вывести на экран сообщение об ошибке и завершится с помощью `os.Exit(1)`.

2022-12-22 16:16 UTC, dshemin commented on hw12_13_14_15_calendar/internal/logger/logger.go
> +func tmpl(tag string, msg string) string {
Важно:

Обратите внимание на стандартный логе Голанга, особенно на флаги которые ему можно установить. Просто вы реализуете то, что уже есть в стандартной библиотеке.

2022-12-22 16:16 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	os.Exit(1)
Критично:

Завершать приложение допустимо ТОЛЬКО из main. Представьте что вы вызовите эту функцию, а у вас после неё будут ещё ряд важных шагов для остановки сервиса?

2022-12-22 16:16 UTC, dshemin commented on hw12_13_14_15_calendar/cmd/calendar/config.go
> +	Logger LoggerConf `yaml:"log"`
Критично:

Не соответствует заданию:

[Работа с хранилищем](https://github.com/OtusGolang/home_work/blob/master/hw12_13_14_15_calendar/docs/12_README.md#3-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-%D1%85%D1%80%D0%B0%D0%BD%D0%B8%D0%BB%D0%B8%D1%89%D0%B5%D0%BC)
> Вынести в конфиг параметр, отвечающий за то, какую из реализаций использовать при старте.
> вынести настройки подключения к БД в конфиг проекта.

[Запуск простого HTTP-сервера](https://github.com/OtusGolang/home_work/blob/master/hw12_13_14_15_calendar/docs/12_README.md#4-%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA-%D0%BF%D1%80%D0%BE%D1%81%D1%82%D0%BE%D0%B3%D0%BE-http-%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80%D0%B0)
> Запуск календаря должен стартовать HTTP-сервер. host и port сервера вынести в конфиг.

2022-12-22 16:16 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/memory/storage.go
> +	s.mu.Lock()
Важно:

Тут должен быть Rlock/Runlock

2022-12-23 12:11 UTC, v4-nikishin commented on hw12_13_14_15_calendar/internal/logger/logger.go
> +func tmpl(tag string, msg string) string {
Это часть ДЗ

2022-12-23 13:54 UTC, v4-nikishin commented on hw12_13_14_15_calendar/cmd/calendar/config.go
> +func LoadConfigFile(cfg interface{}, filePath string) error {
fixed

2022-12-23 13:54 UTC, v4-nikishin commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +		panic(fmt.Sprintf("Failed to configure service %s", err))
fixed

2022-12-23 13:54 UTC, v4-nikishin commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	os.Exit(1)
fixed

2022-12-23 13:54 UTC, v4-nikishin commented on hw12_13_14_15_calendar/internal/storage/memory/storage.go
> +	s.mu.Lock()
fixed

2022-12-24 12:53 UTC, v4-nikishin commented on hw12_13_14_15_calendar/cmd/calendar/config.go
> +	Logger LoggerConf `yaml:"log"`
fixed

2022-12-24 13:24 UTC, dshemin requested changes

2022-12-24 13:24 UTC, dshemin commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +		os.Exit(0)
Важно:

Не, тут делать этого не надо.

2022-12-24 13:24 UTC, dshemin commented on hw12_13_14_15_calendar/internal/logger/logger.go
> +func tmpl(tag string, msg string) string {
Нет, не часть задания. Просто указано что должен быть логгер. Не сказано что вы его должны сами написать.

2022-12-24 13:24 UTC, dshemin commented on hw12_13_14_15_calendar/internal/logger/logger.go
> +func tmpl(tag string, msg string) string {
Более того, вас не ограничивают только стандартным пакетом.

2022-12-24 13:24 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	addr := s.cfg.Host + ":" + s.cfg.Port
Совет:

https://pkg.go.dev/net#JoinHostPort

2022-12-24 13:24 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	server.ListenAndServe()
Важно:

Данный метод возвращает ошибку, например если не смогли забиндить порт так, как он уже занят. Игнорировать ошибку нельзя.

2022-12-24 13:24 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	s.log.Info("...calendar is stopped")
Критично:

Нет логики остановки HTTP сервера, а она должна быть иначе мы просто обрубим соединения с сервером без дообработки существующих соединения!

2022-12-24 13:24 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +func (s *Storage) Connect(dsn string) (err error) {
Важно:

Зачем нам этот публичный метод? Если мы собираемся в коде приводить сторадж к этому типу и вызывать этот метод - у нас течёт абстракция.

2022-12-24 13:24 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	if err := s.connect(); err != nil {
Критично:

Мы будет открывать и закрывать соединение с БД при каждом вызове метода?! Не надо так делать. Мы будем тратить время на установку соединения. 

Надо при создании данного стораджа открыть соединения с БД и после закрыть его когда закрывают сторадж.

2022-12-24 13:24 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +		s.logg.Error(fmt.Sprintf("cannot close psql connection: %v", err))
Важно:

%w вместо %v. Пожалуйста посмотрите ваш код и поправьте везде.

2022-12-24 13:24 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/sql/storage_test.go
> +func TestStorage(t *testing.T) {
Важно:

Это не юнит-тест. Это функциональный или интеграционный тест так, как мы тестируем тут то, как работает приложение с БД. Советую убрать.

2022-12-24 18:58 UTC, v4-nikishin commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	if err := s.connect(); err != nil {
а разве это хуже, чем держать постоянно открытое соединение?

2022-12-24 18:58 UTC, v4-nikishin commented on hw12_13_14_15_calendar/internal/storage/sql/storage_test.go
> +func TestStorage(t *testing.T) {
поэтому здесь я поставил t.Skip()

2022-12-26 10:01 UTC, v4-nikishin commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +		os.Exit(0)
fixed

2022-12-26 10:02 UTC, v4-nikishin commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	addr := s.cfg.Host + ":" + s.cfg.Port
fixed

2022-12-26 10:02 UTC, v4-nikishin commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	server.ListenAndServe()
fixed

2022-12-26 10:06 UTC, v4-nikishin commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	s.log.Info("...calendar is stopped")
fixed

2022-12-26 10:06 UTC, v4-nikishin commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +func (s *Storage) Connect(dsn string) (err error) {
fixed

2022-12-26 10:06 UTC, v4-nikishin commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	if err := s.connect(); err != nil {
fixed

2022-12-26 10:06 UTC, v4-nikishin commented on hw12_13_14_15_calendar/internal/storage/sql/storage_test.go
> +func TestStorage(t *testing.T) {
fixed

2022-12-26 14:17 UTC, dshemin approved these changes

2022-12-26 15:03 UTC, merged