Hw03 frequency analysis
v4-nikishin/hw pull request #3
Opened 2022-09-18 14:08 UTC by v4-nikishin

## Домашнее задание №3 «Частотный анализ»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-09-18 14:39 UTC, antonefremov requested changes
Очень твердая работа и отличный опыт составления сложных алгоритмов. Однако, для тренировки я бы попросил переписать функцию с меньшей временной сложностью и дополнительными юнит-тестами, чтобы правильность выполнения выглядела более убедительно (например, лексикографическая сортировка при одинаковой частоте).

2022-09-18 14:39 UTC, antonefremov commented on hw03_frequency_analysis/top.go
> +			sort.Strings(sk[start:i])
Сложно для понимания и большая временная сложность! А что если n будет сильно больше 10? Сортировка внутри цикла - это не лучшая идея.

2022-09-18 14:41 UTC, antonefremov commented on hw03_frequency_analysis/top_test.go
> +	t.Run("positive test", func(t *testing.T) {
Лучше назвать тесты по-разному и более осмысленно.

2022-09-18 14:47 UTC, v4-nikishin commented on hw03_frequency_analysis/top.go
> +			sort.Strings(sk[start:i])
а разве это не "лексикографическая сортировка при одинаковой частоте"?

2022-09-18 14:51 UTC, v4-nikishin commented on hw03_frequency_analysis/top.go
> +			sort.Strings(sk[start:i])
сортировка происходит в слайсе до индекса i, так что никакой особой проблемы здесь не вижу

2022-09-18 14:55 UTC, v4-nikishin commented on hw03_frequency_analysis/top.go
> +			sort.Strings(sk[start:i])
всё происходит за один проход. в чем заключается "большая временная сложность"?
объясните, пожалуйста?

2022-09-18 14:57 UTC, v4-nikishin commented on hw03_frequency_analysis/top_test.go
> +	t.Run("positive test", func(t *testing.T) {
а в чем будет осмысленность названия, если тесты отличаются только количеством лексем и их частотой?

2022-09-18 23:40 UTC, antonefremov commented on hw03_frequency_analysis/top.go
> +			sort.Strings(sk[start:i])
"Большая временная сложность" заключается в сложности сортировки. Какова сложность сортировки?

2022-09-18 23:56 UTC, antonefremov commented on hw03_frequency_analysis/top_test.go
> +	t.Run("positive test", func(t *testing.T) {
Представьте, что я свежий человек, который только что пришёл на ваш проект. Я хочу понять как ведет себя функция `Top10` на различных наборах тестовых данных. Открываю тесты и вижу какую-то "магию" без пояснений что она тестирует и зачем.
Я просто хотел бы видеть здесь понятный набор тестов с описаниями.

2022-09-19 07:38 UTC, v4-nikishin commented on hw03_frequency_analysis/top.go
> +			sort.Strings(sk[start:i])
Какая разница какова сложность сортировки, если её всё равно надо сделать и именно столько, сколько она выполняется в этом цикле?

2022-09-19 23:40 UTC, antonefremov commented on hw03_frequency_analysis/top.go
> +			sort.Strings(sk[start:i])
Если вы видите подобное "бутылочное горлышко", то обычно это означает, что алгоритм составлен не самым оптимальным образом и его можно улучшить. Бывают, конечно, ситуации, когда квадратичная, кубическая или даже экспоненциальная сложность неизбежны, но тогда и объем обрабатываемых данных будет очень небольшим в единицу времени. В нашем задании объем входных данных или время исполнения не оговариваются, и мне проще чем вам, потому что я уже знаю, что задача может быть решена более оптимально. Поэтому я могу принять ваше решение.

Мне просто хотелось обратить ваше внимание на будущее (не только для этого курса, а вообще), что при написании алгоритмов вам очень желательно видеть сложность наперёд (и временную, и по объему занимаемой памяти) и уметь принимать решения, которые ведут к быстрому и простому для понимания коду.

2022-09-20 03:39 UTC, antonefremov commented on hw03_frequency_analysis/top_test.go
> +	t.Run("different lexemes with the same frequency", func(t *testing.T) {
Гораздо лучше! Такие тесты видеть и читать приятно 👍

2022-09-20 03:39 UTC, antonefremov approved these changes

2022-09-21 01:20 UTC, antonefremov approved these changes

2022-09-21 01:20 UTC, antonefremov approved these changes

2022-09-21 10:19 UTC, antonefremov approved these changes

2022-09-21 16:59 UTC, merged